apiVersion: serving.knative.dev/v1alpha1
kind: Service
metadata:
  name: markdown-validator
  namespace: default
spec:
  runLatest:
    configuration:
      revisionTemplate:
        spec:
          container:
            image: gcr.io/ryangregg-gse-demo/markdown-validator:debug
            env:
            - name: TARGET
              value: "C# Sample v1"